### ISSUE TITLE
I am receiving an error when i try to use the p5.bezier library in editor.

### ISSUE THREAD

**Issue by n-926** [peilingjiang/p5.bezier#10]
🌸 p5.js says: 
[sketch.js, line 6] "newBezier" is not defined in the current scope. If you have defined it in your code, you should check its scope, spelling, and letter-casing (JavaScript is case-sensitive).

Even though this is my first time downloading a library and im new to p5js, i believe i did everything correct, downloaded the p5.bezier file added them into the editor and added the provided script into the html but still recieve the error above

**Comment by peilingjiang** [comment]
Could you please share the link to your p5 editor sketch? You may also refer to this one and see who the library is used - https://editor.p5js.org/peilingjiang/sketches/mVXzWEJbT. You do not have to download the file and upload into the editor folder to use it, and using CDN loading is easier to set up.

**Comment by n-926** [comment]
Thank you copying and pasting the html section in your example and replacing the whole thing with mine seems to work along and adding p5bezier before the code (for beginners this is probably basic info for most sorry for confusion)
