### ISSUE TITLE
Too many points causes curve to be a straight line

### ISSUE THREAD

**Issue by khalby786** [peilingjiang/p5.bezier#12]
I created a simple demo of bezier curves by drawing them, but sometimes the curve tends to shorten to a single line.

For example,

![rVfftJAo7M](https://github.com/user-attachments/assets/4e85ac5e-7211-4c55-99ae-fc8c001da986)

The above consisted of 124 coordinates, all of which were passed to the `newBezier` function to create a curve.

However, if I use slightly more points or draw the same structure differently, the curve seems to shorten to a single point.

![gnWTbTMx5R](https://github.com/user-attachments/assets/1477d015-9eed-4172-962e-b147bc75d938)

This consisted of 261 coordinates. 

This behaviour is visible in curves with ~170 and more coordinates.

Could this be a limitation of bezier curves itself?

**Comment by wh0** [comment]
that's a really high degree curve https://en.wikipedia.org/wiki/B%C3%A9zier_curve#Higher-order_curves. it could be something like numeric overflow, trying to calculate these various coordinates raised to the ~260th power. use multiple lower degree curves instead to avoid this problem https://en.wikipedia.org/wiki/Composite_B%C3%A9zier_curve

**Comment by peilingjiang** [comment]
Thanks for bringing this up! I made some changes so that if the number of points reaches around 170, it will randomly "skip" some of the intermediate points to prevent a memory leak. I'll release a new version later this week.

https://github.com/user-attachments/assets/605a145b-4713-4738-a59f-7a7338415ccb

**Comment by peilingjiang** [comment]
0.7.0 released!
