### ISSUE TITLE
Incorrect point count check in Update() in bezier Object

### ISSUE THREAD

**Issue by Rolands-Laucis** [peilingjiang/p5.bezier#4]
![image](https://user-images.githubusercontent.com/21672819/116786154-dc765380-aaa5-11eb-8764-857ca3c15628.png)

Your docs say that the new array of points must be the same length as when created. True, but there seems to be a typo in the if check code. Clearly the point count is the same. My code that prints to the console:

```
UpdatePoints(amps){

    var p = []

    for(let i = 0; i < this.curve.controlPoints.length; i++){
        p.push([this.curve.controlPoints[i][0], amps[i]*this.max_amp_px])
    }
    console.log('update points length: '+ p.length+' bezier points length: '+ this.curve.controlPoints.length)

    this.curve.update(p)
}
```
After looking in the p5.bezier.min.js, this is the problematic code:

`update(t){if(t.length!==this.controlPoints)throw"The number of points changed. (Keep the point array length the same.)"`

It is not actually checking if the lengths are the same. It should be:
`update(t){if(t.length!==this.controlPoints.length)throw"The number of points changed. (Keep the point array length the same.)"`

That fixes the error.
This error cost me about 1h of frustration, but this is overall a great lib, so i am not complaining.

**Comment by peilingjiang** [comment]
Sorry about that! It's fixed!
