### ISSUE TITLE
Writing to a p5 off-screen renderer doesn't seem to work

### ISSUE THREAD

**Issue by sloosh** [peilingjiang/p5.bezier#6]
I am trying to use your lib with p5 by using an off-screen renderer, but nothing shows.
Here is an example:

let renderer;

function setup() {
  let c = createCanvas(500, 500);
  renderer = createGraphics(500, 500); // off-screen renderer
  
  // Init p5.bezier drawer with the off-screen renderer
  p5bezier.initBezier(renderer);

  // Set styles for the curve
  renderer.noFill();
  renderer.stroke('black');
  renderer.strokeWeight(2);
}

function draw() {
  background(235);

  // Draw the curve
  p5bezier.newBezier([
    [10, 10],
    [100, 700],
    [500, -800],
    [800, 1000],
    [10, 300]
  ]);
  
  // normal bezier function
  renderer.bezier(10, 10, 20, 30, 50, 50, 100, 60);
  
  image(renderer, 0, 0);
  // now the canvas should display the curve made by p5bezier
}

**Comment by peilingjiang** [comment]
Thanks for bringing it up! Fixed with the latest release - 0.3.0.

**Comment by sloosh** [comment]
thanks a lot for the quick fix! works great now :)
