### ISSUE TITLE
node import/require

### ISSUE THREAD

**Issue by ExperiaBe** [peilingjiang/p5.bezier#8]
I get a ReferenceError: self is not defined
    at Object.<anonymous> (.../node_modules/p5bezier/lib/p5.bezier.min.js:2:198)
when using require.

and SyntaxError: Cannot use import statement outside a module
when using import.

I can use all other modules by using require - example: 
chroma = require('chroma-js');

**Comment by peilingjiang** [comment]
Thanks for pointing it out. It has been fixed in the new release of version 0.3.3.

**Comment by peilingjiang** [comment]
The error when using `import` is not directly related to this package itself - you need to set your bundle environment to `module` in order to use JS imports and exports. You may find more information here - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.
